gcs_bucket: tf-state-project-factory-1cea
gcs_prefix: tf-factory
gcp_billing_account_id: 0131D6-94FD9F-065EAB
factory_root: folders/843077510615
group_domain: apszaz.com
group_parent: customers/C018pf49b
tf_service_account: group-creator@project-factory-1cea.iam.gserviceaccount.com
